name: table_calendar
description: Highly customizable, feature-packed calendar widget for Flutter.
version: 3.0.3
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  simple_gesture_detector: ^0.2.0
  card_swiper: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/fonts/
   
   
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
